name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with: 
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn clean install -DskipTests -f pom.xml 
    - name: Extract Version
      id: project
      run: echo "version=$(mvn help:evaluate -Dexpression=project.version -DforceStdout -q)" >> $GITHUB_OUTPUT
    - name: Build the Docker image
      run: | 
        docker build -t opengrower .
        docker tag opengrower ghcr.io/haiku-ai/opengrower:latest
        docker push ghcr.io/haiku-ai/opengrower:latest
      
